services:
  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgrespw
  server:
    image: server
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AI__OpenAI__BaseUrl=http://host.docker.internal:1234/v1
      - ASPNETCORE_URLS=http://+:80
      - AI__OpenAI__ApiKey=lm-studio
      - Client__BaseUrl=https://app.chatapp.com
      - AI__OpenAI__ModelName=lmstudio-ai/gemma-2b-it-GGUF/gemma-2b-it-q8_0.gguf
      - ConnectionStrings__ChatDB=Host=postgres-db;Port=5432;Database=ChatDB;Username=postgres;Password=postgrespw
      - VIRTUAL_HOST=api.chatapp.com
    depends_on:
      - postgres-db
  client-app:
    image: client-app
    build:
      context: .
      dockerfile: src/client-app/Dockerfile
    ports:
      - 3000:3000
    environment:
      - API_SERVER_URL=http://server:80
      - AUTH_SECRET=upAybD3G8XUMzEKTM7fOfmPzHV2Bel5g
      - NEXT_PUBLIC_NOTIFY_SERVER_URL=https://api.chatapp.com/api/v1/notify
      - NEXT_PUBLIC_API_SERVER_URL=https://api.chatapp.com
      - VIRTUAL_HOST=app.chatapp.com
      - VIRTUAL_PORT=3000
    depends_on:
      - server
      - postgres-db
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs